apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: jobber
  name: jobber
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/jobber
spec:
  replicas: 0
  selector:
    matchLabels:
      run: jobber
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: jobber
    spec:
      containers:
      - image: ntfrnzn/job-controller:0.1.5
        imagePullPolicy: Always
        name: jobber
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
